####### sdk.loggers (c) 2024 Archivage Numérique ################################################### MIT License #######
####### https://taskfile.dev

version: '3'

tasks:
    upgrade:
        cmds:
            - go get -u ./...
            - go mod tidy
    lint:
        cmds:
            - golangci-lint run
    test:
        cmds:
            - go test -cover -race ./...
    default:
        cmds:
            - task: lint
            - task: test
    commit:
        cmds:
            - git add .
            - git commit -m "En cours de développement"
            - git push

####### END ############################################################################################################
